### PR TITLE
Version 2.0.0

### PR DESCRIPTION
**Pull request by mbrubeck**
* Requires Rust 1.51 or later.
* Update to arrayvec 0.6, replacing `Array` trait with const generics.
* Remove deprecated methods `evict_all` and `num_entries`.
* Remove quickcheck dev-dependency. (The quickcheck tests have been updated to become standard tests, without losing any coverage.)
* Minor improvements to documentation.

### CODE REVIEW

**Comment by bluss** [comment]
You write clear is removed, but it is (of course) not

**Comment by mbrubeck** [comment]
> You write clear is removed, but it is (of course) not

Oops! Fixed.

**Comment by bluss** [comment]
I guess arrayvec is not a public dep anymore (so it doesn't matter), but the latest version is 0.7.0 with no breaking changes (for you).

**Comment by mbrubeck** [comment]
> I guess arrayvec is not a public dep anymore (so it doesn't matter), but the latest version is 0.7.0 with no breaking changes (for you).

Thanks.  I updated `master` to use arrayvec 0.7 before releasing uluru 2.0.0.

**Pull request merged**
